# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FriendsHub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FriendsHub
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'Moya/RxSwift', '~> 11.0.2'
  pod 'Moya-ModelMapper/RxSwift', '~> 7.1.0'
  pod 'RxOptional'
  pod 'NSObject+Rx'
  pod 'RxSegue', :git => 'https://github.com/RxSwiftCommunity/RxSegue.git'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'GoogleAnalytics'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'FaceAware'
  pod 'BEMCheckBox'
  pod 'DZNEmptyDataSet'
  pod 'PopupKit'
  pod 'IQKeyboardManagerSwift'
  pod 'SideMenu'

  target 'FriendsHubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FriendsHubUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
